# Use a base image
FROM ubuntu:latest

# Install required dependencies
RUN apt-get update && \
    apt-get install -y wget && \
    apt-get install -y git \ 
    build-essential \
    openssl \
    vim \
    xsltproc \
    cmake libssl-dev \
    libwebsockets-dev \
    docbook-xsl


